### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by ofirkris** [AbdulMoqeet/MAFFSRN#3]
Hello, do you have plans to release code and weights?

**Comment by yangyuren03** [comment]
@AbdulMoqeet do you have plan to release code?

**Comment by AbdulMoqeet** [comment]
Hello all,

I am really sorry guys. I will be releasing the code this week along with trained models. 

Regards,
AM

**Comment by ofirkris** [comment]
Thanks! can you upload the trained weights too?

**Comment by liujie183** [comment]
Dear author, will you please provide a more detailed readme file to the source code, thx

**Comment by AbdulMoqeet** [comment]
> Thanks! can you upload the trained weights too?

Sorry for late reply. Unfortunately, I have lost my trained models.

**Comment by AbdulMoqeet** [comment]
> Dear author, will you please provide a more detailed readme file to the source code, thx

Just running the main.py would work for training and testing, with appropriate options.
