### ISSUE TITLE
the question about code

### ISSUE THREAD

**Issue by niliusha123** [AbdulMoqeet/MAFFSRN#4]
what is function of pad in your maffsrn.py, could you please give it, although not used

**Comment by AbdulMoqeet** [comment]
That padding has been used. It's to find the valid padding value.

**Comment by shenhaiyoulan** [comment]
I have the same problem ，I don't know what you mean. Can you make it clear？

**Comment by AbdulMoqeet** [comment]
I'm sorry, I confused the pad with padding type. 


Here is its code (you can add more pad types):
```
def pad(pad_type, padding): 
    pad_type = pad_type.lower()
    if padding == 0:
        return None
    if pad_type == 'reflect':
        layer = nn.ReflectionPad2d(padding)
    elif pad_type == 'replicate':
        layer = nn.ReplicationPad2d(padding)
    else:
        raise NotImplementedError('padding layer [%s] is not implemented' % pad_type)
    return layer
```
